### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by chrisabrams** [njouanin/repool#5]
For my experience: your project works on OS X, but not for Linux.

```
Traceback (most recent call last):
  File "/app/main.py", line 8, in <module>
    from repool import ConnectionPool
  File "/usr/local/lib/python2.7/site-packages/repool/__init__.py", line 1, in <module>
    from .pool import ConnectionPool, ConnectionWrapper
  File "/usr/local/lib/python2.7/site-packages/repool/pool.py", line 19, in <module>
    from queue import Queue
ImportError: No module named queue
```

**Comment by gbnk0** [comment]
it's because the "queue" module is only in python3,

**Comment by gbnk0** [comment]
It will be fixed in this:
https://github.com/njouanin/repool/pull/4
